// Package detector — Native Go TF-IDF + Logistic Regression scorer.
//
// Replicates sklearn's TfidfVectorizer + LogisticRegression pipeline in pure Go:
//
//	1. Tokenise command on whitespace  (token_pattern=r"[^\s]+")
//	2. Generate 1-grams and 2-grams    (ngram_range=(1, 2))
//	3. Sublinear TF:  tf = log(count) + 1   for count > 0
//	4. Multiply by stored IDF weights
//	5. L2 normalise the sparse vector
//	6. Dot-product with LR coefficients + intercept → log-odds
//	7. Sigmoid → P(malicious)  →  risk score 0–100
//
// The model is loaded from data/trained_model.json, which is generated by
// running:  python scripts/export_model.py
package detector

import (
	"encoding/json"
	"log/slog"
	"math"
	"os"
	"strings"
	"sync"
)

// ── JSON model schema ─────────────────────────────────────────────────────────

type modelJSON struct {
	Vocabulary map[string]int `json:"vocabulary"`
	IDF        []float64      `json:"idf"`
	Coef       []float64      `json:"coef"`
	Intercept  float64        `json:"intercept"`
}

// ── MLScorer ──────────────────────────────────────────────────────────────────

// MLScorer performs TF-IDF vectorisation and Logistic Regression inference
// in native Go — zero Python dependency at runtime.
type MLScorer struct {
	vocab    map[string]int
	idf      []float64
	coef     []float64
	intercept float64
	ready    bool
}

var (
	mlScorerOnce      sync.Once
	mlScorerSingleton *MLScorer
)

// GetMLScorer returns the package-level MLScorer singleton.
// modelPath should point to data/trained_model.json.
// If the file is absent the scorer operates in degraded mode (returns 0, 0).
func GetMLScorer(modelPath string) *MLScorer {
	mlScorerOnce.Do(func() {
		s, err := newMLScorer(modelPath)
		if err != nil {
			slog.Warn("MLScorer: model not loaded — ML scoring disabled", "err", err)
			s = &MLScorer{ready: false}
		}
		mlScorerSingleton = s
	})
	return mlScorerSingleton
}

func newMLScorer(modelPath string) (*MLScorer, error) {
	data, err := os.ReadFile(modelPath)
	if err != nil {
		return nil, err
	}

	var m modelJSON
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, err
	}

	slog.Info("MLScorer: model loaded",
		"features", len(m.Vocabulary),
		"path", modelPath,
	)

	return &MLScorer{
		vocab:    m.Vocabulary,
		idf:      m.IDF,
		coef:     m.Coef,
		intercept: m.Intercept,
		ready:    true,
	}, nil
}

// Score computes the malicious-class probability for a command.
//
// Returns:
//   - riskScore  — P(malicious) × 100, range 0–100
//   - confidence — max(P(safe), P(malicious)), range 0.5–1.0
//
// Returns (0, 0) when the model is unavailable.
func (m *MLScorer) Score(command string) (riskScore, confidence float64) {
	if !m.ready {
		return 0, 0
	}

	// ── Step 1: tokenise ──────────────────────────────────────────────────────
	tokens := tokenise(command)
	if len(tokens) == 0 {
		return 0, 0
	}

	// ── Step 2: n-gram generation (1-gram + 2-gram) ───────────────────────────
	ngrams := buildNgrams(tokens)

	// ── Step 3 & 4: raw TF → sublinear TF → × IDF (sparse) ──────────────────
	// We use a map to accumulate raw counts first.
	rawCounts := make(map[int]float64, len(ngrams))
	for _, gram := range ngrams {
		if idx, ok := m.vocab[gram]; ok {
			rawCounts[idx]++
		}
	}

	// Apply sublinear TF and IDF.
	tfidf := make(map[int]float64, len(rawCounts))
	for idx, count := range rawCounts {
		tf := math.Log(count) + 1.0 // sublinear TF: log(count) + 1
		tfidf[idx] = tf * m.idf[idx]
	}

	// ── Step 5: L2 normalise ──────────────────────────────────────────────────
	var norm float64
	for _, v := range tfidf {
		norm += v * v
	}
	norm = math.Sqrt(norm)
	if norm > 0 {
		for idx := range tfidf {
			tfidf[idx] /= norm
		}
	}

	// ── Step 6: LR decision function  (sparse dot-product) ───────────────────
	score := m.intercept
	for idx, v := range tfidf {
		score += m.coef[idx] * v
	}

	// ── Step 7: sigmoid → risk score ─────────────────────────────────────────
	probMalicious := sigmoid(score)
	probSafe := 1.0 - probMalicious

	riskScore = probMalicious * 100.0
	confidence = math.Max(probMalicious, probSafe)
	return riskScore, confidence
}

// IsReady reports whether the ML model was loaded successfully.
func (m *MLScorer) IsReady() bool {
	return m.ready
}

// ── Helpers ───────────────────────────────────────────────────────────────────

// tokenise splits a command into tokens exactly as sklearn's
// token_pattern=r"[^\s]+" does: any maximal sequence of non-whitespace chars.
func tokenise(command string) []string {
	return strings.Fields(command) // strings.Fields splits on any whitespace
}

// buildNgrams generates all 1-grams and 2-grams for a token slice,
// joining 2-grams with a single space (sklearn's default separator).
func buildNgrams(tokens []string) []string {
	out := make([]string, 0, len(tokens)*2)

	// 1-grams
	out = append(out, tokens...)

	// 2-grams
	for i := 0; i < len(tokens)-1; i++ {
		out = append(out, tokens[i]+" "+tokens[i+1])
	}

	return out
}

// sigmoid computes the logistic function 1 / (1 + e^-x).
func sigmoid(x float64) float64 {
	return 1.0 / (1.0 + math.Exp(-x))
}
